apiVersion: v2
name: neuraltrust-data-plane
description: Data Plane components for NeuralTrust
type: application
version: 0.1.0
dependencies:
  - name: clickhouse
    version: 8.0.10
    repository: "file://../../clickhouse"
    condition: dataPlane.components.clickhouse.enabled
    # ClickHouse must be installed first
  - name: kafka
    version: 31.0.0
    repository: "file://../../kafka"
    condition: dataPlane.components.kafka.enabled
    dependsOn:
      - clickhouse
    # Kafka depends on ClickHouse, so it will be installed after ClickHouse